### ISSUE TITLE
Journey mod research and other sugestions

### ISSUE THREAD

**Issue by Lion8cake** [HiKoNe/LiquidLib#1]
Hello I have been testing around with this for a while and it feels really well done. I found one bug and have many suggestions for the mod. 
The bug I found was that the modded bucket can't be researched in journey mode.
I have a few suggestions for the mod as well.
1. Moddded liquid sensor 
it would be really cool to also make a modded liquid sensor with your own modded liquid
2. Custom bubbles
I like how it uses water bubbles as of now but the modded liquid I would like to make has custom bubbles similar to lava
3. Have the liquid apply a custom debuff
I haven't really messed around with modded liquids and debuff/buffs yet but I would assume that this wouldn't be possible yet

A really awesome job at this mod and I will defiantly be using it the future to create my own liquids, keep up the good work.
(Im am completely understandable if some of the suggestions can't be done)
-Lion8cake

**Comment by FunCrafter1234** [comment]
The only thing LiquidLib should still add is the Journey Mode reaseach. But all other things are your job.
The sensor is your problem. Liquid Lib adds all functionality needed for a tile to check if a modded liquid is close. You could easily do that. It would be stupid to autogenerate these because not everyone would want a sensor for their liquid.
And Custom bubbles are basically just Dusts... that also is your thing to program in override OnUpdate()
And custom debuffs are as easy as OnLiquidIn() and checking if the entity is an NPC or Player then you can just add a Debuff / Buff to your like I have done it already.

**Comment by Lion8cake** [comment]
> The only thing LiquidLib should still add is the Journey Mode reaseach. But all other things are your job.
> The sensor is your problem. Liquid Lib adds all functionality needed for a tile to check if a modded liquid is close. You could easily do that. It would be stupid to autogenerate these because not everyone would want a sensor for their liquid.
> And Custom bubbles are basically just Dusts... that also is your thing to program in override OnUpdate()
> And custom debuffs are as easy as OnLiquidIn() and checking if the entity is an NPC or Player then you can just add a Debuff / Buff to your like I have done it already.

Ah ok I wasn't to sure on how to do the sensor so thanks. the custom bubbles I was referring too is when you are submerged under the liquid your given 10 bubbles before taking damage, I wanted to make my own type of bubbles when submerged under my own liquid instead of just having the default water bubbles. Anyways thanks.

**Comment by HiKoNe** [comment]
> > The only thing LiquidLib should still add is the Journey Mode reaseach. But all other things are your job.
> > The sensor is your problem. Liquid Lib adds all functionality needed for a tile to check if a modded liquid is close. You could easily do that. It would be stupid to autogenerate these because not everyone would want a sensor for their liquid.
> > And Custom bubbles are basically just Dusts... that also is your thing to program in override OnUpdate()
> > And custom debuffs are as easy as OnLiquidIn() and checking if the entity is an NPC or Player then you can just add a Debuff / Buff to your like I have done it already.
> 
> Ah ok I wasn't to sure on how to do the sensor so thanks. the custom bubbles I was referring too is when you are submerged under the liquid your given 10 bubbles before taking damage, I wanted to make my own type of bubbles when submerged under my own liquid instead of just having the default water bubbles. Anyways thanks.

Oh, i understand, i need fix it

**Comment by HiKoNe** [comment]
I fix: Journey mod research, Water liquid sensor, pumps. Also i add new Property "Drown" see wiki
